name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

      - name: Check for backend changes
        if: steps.changes.outputs.backend == 'true'
        id: backend-task
        run: |
          echo "backend changed."

      - name: Check for frontend changes
        if: steps.changes.outputs.frontend == 'true'
        id: frontend-task
        run: |
          echo "frontend changed."