name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get changed folders
        id: get-changed-folders
        run: |
          echo "backend changed."